spring:
  # datasource
  datasource:
    url: jdbc:mysql://120.27.224.128:3306/mall_promotion?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ${MALL_MYSQL_PASSWORD}
